version: '3.5'
services:

  # POSTGRESQL CONTAINER
  user-db:
    image: postgres:alpine
    ports:
    - '28182:5432'
    container_name: LPDM-User
    environment:
      POSTGRES_DB: lpdm-user
      POSTGRES_USER: lpdm
      POSTGRES_PASSWORD: lpdm
    volumes:
    - './db/sql:/docker-entrypoint-initdb.d'
    restart: always
    network_mode: bridge